networks:
  debezium-network:
    driver: bridge
    name: debezium-network

services:
  # PostgreSQL Source Database
  postgres-transactional:
    image: postgres:15
    container_name: postgres-transactional
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/transactional-init.sql:/docker-entrypoint-initdb.d/transactional-init.sql
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./transactional-pgdata:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - debezium-network

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - debezium-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    healthcheck:
      test:
        ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - debezium-network

  # Kafka Connect with Debezium
  kafka-connect:
    image: debezium/connect:2.4
    container_name: kafka-connect
    depends_on:
      kafka:
        condition: service_healthy
      postgres-transactional:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083/connectors || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - debezium-network

  # Connector Deployer
  connector-deployer:
    build: ./connector-deployer
    container_name: connector-deployer
    depends_on:
      kafka-connect:
        condition: service_healthy
    environment:
      KAFKA_CONNECT_URL: http://kafka-connect:8083
      CONNECTOR_NAME: postgres-connector
      MAX_RETRIES: 30
      RETRY_DELAY: 10
    restart: "no"
    networks:
      - debezium-network

  # Analytics PostgreSQL Database
  postgres-analytics:
    image: postgres:15
    container_name: postgres-analytics
    environment:
      POSTGRES_DB: analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/analytics-init.sql:/docker-entrypoint-initdb.d/analytics-init.sql
      - ./analytics-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - debezium-network

  # Analytics Consumer
  analytics-consumer:
    build: ./analytics-consumer
    container_name: analytics-consumer
    depends_on:
      kafka:
        condition: service_healthy
      postgres-analytics:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      ANALYTICS_DB_HOST: postgres-analytics
      ANALYTICS_DB_PORT: 5432
      ANALYTICS_DB_NAME: analytics
      ANALYTICS_DB_USER: postgres
      ANALYTICS_DB_PASSWORD: postgres
    restart: unless-stopped
    networks:
      - debezium-network

  # Transactional Dataloader
  transactional-dataloader:
    build: ./transactional-dataloader
    container_name: transactional-dataloader
    depends_on:
      kafka:
        condition: service_healthy
      postgres-transactional:
        condition: service_healthy
    environment:
      TRANSACTIONAL_DB_HOST: postgres-transactional
      TRANSACTIONAL_DB_PORT: 5432
      TRANSACTIONAL_DB_NAME: ecommerce
      TRANSACTIONAL_DB_USER: postgres
      TRANSACTIONAL_DB_PASSWORD: postgres
      # Data loader configuration
      SPEED_MULTIPLIER: 10.0
      DURATION_HOURS: 2.0
      CLEAR_DATA: true
    networks:
      - debezium-network

  # Metabase for Analytics Visualization
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      postgres-analytics:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      JAVA_TIMEZONE: UTC
    volumes:
      - ./metabase-data:/metabase-data
    restart: unless-stopped
    networks:
      - debezium-network
